# 2017 step1

# ele ########################################

#python step1_select.py --version v2 --year 2017 --flavour ele --logLevel INFO --ptSelection pt_5_-1   --sample DYJetsToLL_M10to50_LO #SPLIT239
#python step1_select.py --version v2 --year 2017 --flavour ele --logLevel INFO --ptSelection pt_5_-1   --sample DYJetsToLL_M4to50_HT100to200_LO #SPLIT57
#python step1_select.py --version v2 --year 2017 --flavour ele --logLevel INFO --ptSelection pt_5_-1   --sample DYJetsToLL_M4to50_HT100to200_LO_ext1 #SPLIT8
#python step1_select.py --version v2 --year 2017 --flavour ele --logLevel INFO --ptSelection pt_5_-1   --sample DYJetsToLL_M4to50_HT200to400_new_pmx_LO #SPLIT23
#python step1_select.py --version v2 --year 2017 --flavour ele --logLevel INFO --ptSelection pt_5_-1   --sample DYJetsToLL_M4to50_HT200to400_LO #SPLIT28
#python step1_select.py --version v2 --year 2017 --flavour ele --logLevel INFO --ptSelection pt_5_-1   --sample DYJetsToLL_M4to50_HT200to400_LO_ext1 #SPLIT10
#python step1_select.py --version v2 --year 2017 --flavour ele --logLevel INFO --ptSelection pt_5_-1   --sample DYJetsToLL_M4to50_HT400to600_LO #SPLIT16
#python step1_select.py --version v2 --year 2017 --flavour ele --logLevel INFO --ptSelection pt_5_-1   --sample DYJetsToLL_M4to50_HT400to600_LO_ext1 #SPLIT10
#python step1_select.py --version v2 --year 2017 --flavour ele --logLevel INFO --ptSelection pt_5_-1   --sample DYJetsToLL_M4to50_HT600toInf_LO #SPLIT17
#python step1_select.py --version v2 --year 2017 --flavour ele --logLevel INFO --ptSelection pt_5_-1   --sample DYJetsToLL_M4to50_HT600toInf_LO_ext1 #SPLIT24
#python step1_select.py --version v2 --year 2017 --flavour ele --logLevel INFO --ptSelection pt_5_-1   --sample DYJetsToLL_M50_NLO #SPLIT1003
#python step1_select.py --version v2 --year 2017 --flavour ele --logLevel INFO --ptSelection pt_5_-1   --sample DYJetsToLL_M50_LO #SPLIT277
#python step1_select.py --version v2 --year 2017 --flavour ele --logLevel INFO --ptSelection pt_5_-1   --sample DYJetsToLL_M50_LO_ext1 #SPLIT295
#python step1_select.py --version v2 --year 2017 --flavour ele --logLevel INFO --ptSelection pt_5_-1   --sample DYJetsToLL_M50_HT70to100_LO #SPLIT104
#python step1_select.py --version v2 --year 2017 --flavour ele --logLevel INFO --ptSelection pt_5_-1   --sample DYJetsToLL_M50_HT100to200_LO #SPLIT31
#python step1_select.py --version v2 --year 2017 --flavour ele --logLevel INFO --ptSelection pt_5_-1   --sample DYJetsToLL_M50_HT100to200_LO_ext1 #SPLIT86
#python step1_select.py --version v2 --year 2017 --flavour ele --logLevel INFO --ptSelection pt_5_-1   --sample DYJetsToLL_M50_HT200to400_LO #SPLIT80
#python step1_select.py --version v2 --year 2017 --flavour ele --logLevel INFO --ptSelection pt_5_-1   --sample DYJetsToLL_M50_HT200to400_LO_ext1 #SPLIT11
#python step1_select.py --version v2 --year 2017 --flavour ele --logLevel INFO --ptSelection pt_5_-1   --sample DYJetsToLL_M50_HT400to600_LO #SPLIT12
#python step1_select.py --version v2 --year 2017 --flavour ele --logLevel INFO --ptSelection pt_5_-1   --sample DYJetsToLL_M50_HT400to600_LO_ext1 #SPLIT97
#python step1_select.py --version v2 --year 2017 --flavour ele --logLevel INFO --ptSelection pt_5_-1   --sample DYJetsToLL_M50_HT600to800_LO #SPLIT92
#python step1_select.py --version v2 --year 2017 --flavour ele --logLevel INFO --ptSelection pt_5_-1   --sample DYJetsToLL_M50_HT800to1200_LO #SPLIT33
#python step1_select.py --version v2 --year 2017 --flavour ele --logLevel INFO --ptSelection pt_5_-1   --sample DYJetsToLL_M50_HT1200to2500_LO #SPLIT8
#python step1_select.py --version v2 --year 2017 --flavour ele --logLevel INFO --ptSelection pt_5_-1   --sample DYJetsToLL_M50_HT2500toInf_LO #SPLIT6

#python step1_select.py --version v2 --year 2017 --flavour ele --logLevel INFO --ptSelection pt_5_-1   --sample QCD_EMEnriched_pt20to30 #SPLIT63
#python step1_select.py --version v2 --year 2017 --flavour ele --logLevel INFO --ptSelection pt_5_-1   --sample QCD_EMEnriched_pt30to50 #SPLIT88
#python step1_select.py --version v2 --year 2017 --flavour ele --logLevel INFO --ptSelection pt_5_-1   --sample QCD_EMEnriched_pt50to80 #SPLIT64
#python step1_select.py --version v2 --year 2017 --flavour ele --logLevel INFO --ptSelection pt_5_-1   --sample QCD_EMEnriched_pt80to120 #SPLIT53
#python step1_select.py --version v2 --year 2017 --flavour ele --logLevel INFO --ptSelection pt_5_-1   --sample QCD_EMEnriched_pt120to170 #SPLIT171
#python step1_select.py --version v2 --year 2017 --flavour ele --logLevel INFO --ptSelection pt_5_-1   --sample QCD_EMEnriched_pt170to300 #SPLIT36
#python step1_select.py --version v2 --year 2017 --flavour ele --logLevel INFO --ptSelection pt_5_-1   --sample QCD_EMEnriched_pt300toInf #SPLIT25
#python step1_select.py --version v2 --year 2017 --flavour ele --logLevel INFO --ptSelection pt_5_-1   --sample QCD_bcToE_pt20to30_new_pmx #SPLIT125
#python step1_select.py --version v2 --year 2017 --flavour ele --logLevel INFO --ptSelection pt_5_-1   --sample QCD_bcToE_pt20to30 #SPLIT57
#python step1_select.py --version v2 --year 2017 --flavour ele --logLevel INFO --ptSelection pt_5_-1   --sample QCD_bcToE_pt30to80 #SPLIT93
#python step1_select.py --version v2 --year 2017 --flavour ele --logLevel INFO --ptSelection pt_5_-1   --sample QCD_bcToE_pt80to170 #SPLIT95
#python step1_select.py --version v2 --year 2017 --flavour ele --logLevel INFO --ptSelection pt_5_-1   --sample QCD_bcToE_pt170to250 #SPLIT89
#python step1_select.py --version v2 --year 2017 --flavour ele --logLevel INFO --ptSelection pt_5_-1   --sample QCD_bcToE_pt250toInf #SPLIT94

#python step1_select.py --version v2 --year 2017 --flavour ele --logLevel INFO --ptSelection pt_5_-1   --sample ST_schannel_4f_NLO #SPLIT71
#python step1_select.py --version v2 --year 2017 --flavour ele --logLevel INFO --ptSelection pt_5_-1   --sample ST_schannel_4f_NLO_PS #SPLIT74
#python step1_select.py --version v2 --year 2017 --flavour ele --logLevel INFO --ptSelection pt_5_-1   --sample ST_tchannel_antitop_4f_incl_pow #SPLIT33
#python step1_select.py --version v2 --year 2017 --flavour ele --logLevel INFO --ptSelection pt_5_-1   --sample ST_tchannel_top_4f_incl_pow #SPLIT47
#python step1_select.py --version v2 --year 2017 --flavour ele --logLevel INFO --ptSelection pt_5_-1   --sample ST_tchannel_antitop_5f_pow_PS #SPLIT30
#python step1_select.py --version v2 --year 2017 --flavour ele --logLevel INFO --ptSelection pt_5_-1   --sample ST_tchannel_antitop_5f_pow_PS_old_pmx #SPLIT66
#python step1_select.py --version v2 --year 2017 --flavour ele --logLevel INFO --ptSelection pt_5_-1   --sample ST_tchannel_top_5f_pow_old_pmx #SPLIT96
#python step1_select.py --version v2 --year 2017 --flavour ele --logLevel INFO --ptSelection pt_5_-1   --sample ST_tchannel_top_5f_pow #SPLIT45
#python step1_select.py --version v2 --year 2017 --flavour ele --logLevel INFO --ptSelection pt_5_-1   --sample ST_tW_antitop_NoFullyHad_5f_pow_PS #SPLIT48
#python step1_select.py --version v2 --year 2017 --flavour ele --logLevel INFO --ptSelection pt_5_-1   --sample ST_tW_antitop_incl_5f_pow #SPLIT67
#python step1_select.py --version v2 --year 2017 --flavour ele --logLevel INFO --ptSelection pt_5_-1   --sample ST_tW_antitop_incl_5f_pow_PS #SPLIT75
#python step1_select.py --version v2 --year 2017 --flavour ele --logLevel INFO --ptSelection pt_5_-1   --sample ST_tW_top_NoFullyHad_5f_pow #SPLIT47
#python step1_select.py --version v2 --year 2017 --flavour ele --logLevel INFO --ptSelection pt_5_-1   --sample ST_tW_top_NoFullyHad_5f_pow_PS #SPLIT44
#python step1_select.py --version v2 --year 2017 --flavour ele --logLevel INFO --ptSelection pt_5_-1   --sample ST_tW_top_incl_5f_pow #SPLIT70
#python step1_select.py --version v2 --year 2017 --flavour ele --logLevel INFO --ptSelection pt_5_-1   --sample ST_tW_top_incl_5f_pow_PS #SPLIT57
#python step1_select.py --version v2 --year 2017 --flavour ele --logLevel INFO --ptSelection pt_5_-1   --sample ST_tWll_5f_LO #SPLIT21
#python step1_select.py --version v2 --year 2017 --flavour ele --logLevel INFO --ptSelection pt_5_-1   --sample ST_tWnunu_5f_LO #SPLIT6

#python step1_select.py --version v2 --year 2017 --flavour ele --logLevel INFO --ptSelection pt_5_-1   --sample TTJets_NLO #SPLIT1265
#python step1_select.py --version v2 --year 2017 --flavour ele --logLevel INFO --ptSelection pt_5_-1   --sample TTJets_LO #SPLIT131
#python step1_select.py --version v2 --year 2017 --flavour ele --logLevel INFO --ptSelection pt_5_-1   --sample TTJets_semilepFromT_LO #SPLIT526
#python step1_select.py --version v2 --year 2017 --flavour ele --logLevel INFO --ptSelection pt_5_-1   --sample TTJets_semilepFromTbar_LO #SPLIT654
#python step1_select.py --version v2 --year 2017 --flavour ele --logLevel INFO --ptSelection pt_5_-1   --sample TTJets_dilep_LO #SPLIT301
#python step1_select.py --version v2 --year 2017 --flavour ele --logLevel INFO --ptSelection pt_5_-1   --sample TTJets_semilepFromT_genMET150_LO #SPLIT237
#python step1_select.py --version v2 --year 2017 --flavour ele --logLevel INFO --ptSelection pt_5_-1   --sample TTJets_semilepFromTbar_genMET150_LO #SPLIT130
#python step1_select.py --version v2 --year 2017 --flavour ele --logLevel INFO --ptSelection pt_5_-1   --sample TTJets_dilep_genMET150_LO #SPLIT188
#python step1_select.py --version v2 --year 2017 --flavour ele --logLevel INFO --ptSelection pt_5_-1   --sample TTTo2L2Nu_pow #SPLIT77
#python step1_select.py --version v2 --year 2017 --flavour ele --logLevel INFO --ptSelection pt_5_-1   --sample TTTo2L2Nu_pow_PS #SPLIT526
#python step1_select.py --version v2 --year 2017 --flavour ele --logLevel INFO --ptSelection pt_5_-1   --sample TTToSemiLeptonic_pow #SPLIT415
#python step1_select.py --version v2 --year 2017 --flavour ele --logLevel INFO --ptSelection pt_5_-1   --sample TTToSemiLeptonic_pow_PS #SPLIT1086
#python step1_select.py --version v2 --year 2017 --flavour ele --logLevel INFO --ptSelection pt_5_-1   --sample TTHH_LO #SPLIT3
#python step1_select.py --version v2 --year 2017 --flavour ele --logLevel INFO --ptSelection pt_5_-1   --sample TTZH_LO #SPLIT4
#python step1_select.py --version v2 --year 2017 --flavour ele --logLevel INFO --ptSelection pt_5_-1   --sample TTWH_LO #SPLIT3
#python step1_select.py --version v2 --year 2017 --flavour ele --logLevel INFO --ptSelection pt_5_-1   --sample TTWW_LO #SPLIT3
#python step1_select.py --version v2 --year 2017 --flavour ele --logLevel INFO --ptSelection pt_5_-1   --sample TTWZ_LO #SPLIT3
#python step1_select.py --version v2 --year 2017 --flavour ele --logLevel INFO --ptSelection pt_5_-1   --sample TTZZ_LO #SPLIT3
#python step1_select.py --version v2 --year 2017 --flavour ele --logLevel INFO --ptSelection pt_5_-1   --sample TTJets_HT600to800_LO #SPLIT1168
#python step1_select.py --version v2 --year 2017 --flavour ele --logLevel INFO --ptSelection pt_5_-1   --sample TTJets_HT800to1200_LO #SPLIT577
#python step1_select.py --version v2 --year 2017 --flavour ele --logLevel INFO --ptSelection pt_5_-1   --sample TTJets_HT1200to2500_LO #SPLIT271
#python step1_select.py --version v2 --year 2017 --flavour ele --logLevel INFO --ptSelection pt_5_-1   --sample TTJets_HT2500toInf_LO #SPLIT142

# muo ########################################

#python step1_select.py --version v2 --year 2017 --flavour muo --logLevel INFO --ptSelection pt_3.5_-1   --sample DYJetsToLL_M10to50_LO #SPLIT239
#python step1_select.py --version v2 --year 2017 --flavour muo --logLevel INFO --ptSelection pt_3.5_-1   --sample DYJetsToLL_M4to50_HT100to200_LO #SPLIT57
#python step1_select.py --version v2 --year 2017 --flavour muo --logLevel INFO --ptSelection pt_3.5_-1   --sample DYJetsToLL_M4to50_HT100to200_LO_ext1 #SPLIT8
#python step1_select.py --version v2 --year 2017 --flavour muo --logLevel INFO --ptSelection pt_3.5_-1   --sample DYJetsToLL_M4to50_HT200to400_new_pmx_LO #SPLIT23
#python step1_select.py --version v2 --year 2017 --flavour muo --logLevel INFO --ptSelection pt_3.5_-1   --sample DYJetsToLL_M4to50_HT200to400_LO #SPLIT28
#python step1_select.py --version v2 --year 2017 --flavour muo --logLevel INFO --ptSelection pt_3.5_-1   --sample DYJetsToLL_M4to50_HT200to400_LO_ext1 #SPLIT10
#python step1_select.py --version v2 --year 2017 --flavour muo --logLevel INFO --ptSelection pt_3.5_-1   --sample DYJetsToLL_M4to50_HT400to600_LO #SPLIT16
#python step1_select.py --version v2 --year 2017 --flavour muo --logLevel INFO --ptSelection pt_3.5_-1   --sample DYJetsToLL_M4to50_HT400to600_LO_ext1 #SPLIT10
#python step1_select.py --version v2 --year 2017 --flavour muo --logLevel INFO --ptSelection pt_3.5_-1   --sample DYJetsToLL_M4to50_HT600toInf_LO #SPLIT17
#python step1_select.py --version v2 --year 2017 --flavour muo --logLevel INFO --ptSelection pt_3.5_-1   --sample DYJetsToLL_M4to50_HT600toInf_LO_ext1 #SPLIT24
#python step1_select.py --version v2 --year 2017 --flavour muo --logLevel INFO --ptSelection pt_3.5_-1   --sample DYJetsToLL_M50_NLO #SPLIT1003
#python step1_select.py --version v2 --year 2017 --flavour muo --logLevel INFO --ptSelection pt_3.5_-1   --sample DYJetsToLL_M50_LO #SPLIT277
#python step1_select.py --version v2 --year 2017 --flavour muo --logLevel INFO --ptSelection pt_3.5_-1   --sample DYJetsToLL_M50_LO_ext1 #SPLIT295
#python step1_select.py --version v2 --year 2017 --flavour muo --logLevel INFO --ptSelection pt_3.5_-1   --sample DYJetsToLL_M50_HT70to100_LO #SPLIT104
#python step1_select.py --version v2 --year 2017 --flavour muo --logLevel INFO --ptSelection pt_3.5_-1   --sample DYJetsToLL_M50_HT100to200_LO #SPLIT31
#python step1_select.py --version v2 --year 2017 --flavour muo --logLevel INFO --ptSelection pt_3.5_-1   --sample DYJetsToLL_M50_HT100to200_LO_ext1 #SPLIT86
#python step1_select.py --version v2 --year 2017 --flavour muo --logLevel INFO --ptSelection pt_3.5_-1   --sample DYJetsToLL_M50_HT200to400_LO #SPLIT80
#python step1_select.py --version v2 --year 2017 --flavour muo --logLevel INFO --ptSelection pt_3.5_-1   --sample DYJetsToLL_M50_HT200to400_LO_ext1 #SPLIT11
#python step1_select.py --version v2 --year 2017 --flavour muo --logLevel INFO --ptSelection pt_3.5_-1   --sample DYJetsToLL_M50_HT400to600_LO #SPLIT12
#python step1_select.py --version v2 --year 2017 --flavour muo --logLevel INFO --ptSelection pt_3.5_-1   --sample DYJetsToLL_M50_HT400to600_LO_ext1 #SPLIT97
#python step1_select.py --version v2 --year 2017 --flavour muo --logLevel INFO --ptSelection pt_3.5_-1   --sample DYJetsToLL_M50_HT600to800_LO #SPLIT92
#python step1_select.py --version v2 --year 2017 --flavour muo --logLevel INFO --ptSelection pt_3.5_-1   --sample DYJetsToLL_M50_HT800to1200_LO #SPLIT33
#python step1_select.py --version v2 --year 2017 --flavour muo --logLevel INFO --ptSelection pt_3.5_-1   --sample DYJetsToLL_M50_HT1200to2500_LO #SPLIT8
#python step1_select.py --version v2 --year 2017 --flavour muo --logLevel INFO --ptSelection pt_3.5_-1   --sample DYJetsToLL_M50_HT2500toInf_LO #SPLIT6

#python step1_select.py --version v2 --year 2017 --flavour muo --logLevel INFO --ptSelection pt_3.5_-1   --sample QCD_Mu_pt15to20 #SPLIT32
#python step1_select.py --version v2 --year 2017 --flavour muo --logLevel INFO --ptSelection pt_3.5_-1   --sample QCD_Mu_pt20to30 #SPLIT160
#python step1_select.py --version v2 --year 2017 --flavour muo --logLevel INFO --ptSelection pt_3.5_-1   --sample QCD_Mu_pt30to50 #SPLIT163
#python step1_select.py --version v2 --year 2017 --flavour muo --logLevel INFO --ptSelection pt_3.5_-1   --sample QCD_Mu_pt50to80 #SPLIT145
#python step1_select.py --version v2 --year 2017 --flavour muo --logLevel INFO --ptSelection pt_3.5_-1   --sample QCD_Mu_pt80to120 #SPLIT145
#python step1_select.py --version v2 --year 2017 --flavour muo --logLevel INFO --ptSelection pt_3.5_-1   --sample QCD_Mu_pt120to170 #SPLIT171
#python step1_select.py --version v2 --year 2017 --flavour muo --logLevel INFO --ptSelection pt_3.5_-1   --sample QCD_Mu_pt170to300 #SPLIT360
#python step1_select.py --version v2 --year 2017 --flavour muo --logLevel INFO --ptSelection pt_3.5_-1   --sample QCD_Mu_pt300to470 #SPLIT186
#python step1_select.py --version v2 --year 2017 --flavour muo --logLevel INFO --ptSelection pt_3.5_-1   --sample QCD_Mu_pt470to600 #SPLIT191
#python step1_select.py --version v2 --year 2017 --flavour muo --logLevel INFO --ptSelection pt_3.5_-1   --sample QCD_Mu_pt600to800 #SPLIT196
#python step1_select.py --version v2 --year 2017 --flavour muo --logLevel INFO --ptSelection pt_3.5_-1   --sample QCD_Mu_pt800to1000 #SPLIT192
#python step1_select.py --version v2 --year 2017 --flavour muo --logLevel INFO --ptSelection pt_3.5_-1   --sample QCD_Mu_pt1000toInf #SPLIT129

#python step1_select.py --version v2 --year 2017 --flavour muo --logLevel INFO --ptSelection pt_3.5_-1   --sample ST_schannel_4f_NLO #SPLIT71
#python step1_select.py --version v2 --year 2017 --flavour muo --logLevel INFO --ptSelection pt_3.5_-1   --sample ST_schannel_4f_NLO_PS #SPLIT74
#python step1_select.py --version v2 --year 2017 --flavour muo --logLevel INFO --ptSelection pt_3.5_-1   --sample ST_tchannel_antitop_4f_incl_pow #SPLIT33
#python step1_select.py --version v2 --year 2017 --flavour muo --logLevel INFO --ptSelection pt_3.5_-1   --sample ST_tchannel_top_4f_incl_pow #SPLIT47
#python step1_select.py --version v2 --year 2017 --flavour muo --logLevel INFO --ptSelection pt_3.5_-1   --sample ST_tchannel_antitop_5f_pow_PS #SPLIT30
#python step1_select.py --version v2 --year 2017 --flavour muo --logLevel INFO --ptSelection pt_3.5_-1   --sample ST_tchannel_antitop_5f_pow_PS_old_pmx #SPLIT66
#python step1_select.py --version v2 --year 2017 --flavour muo --logLevel INFO --ptSelection pt_3.5_-1   --sample ST_tchannel_top_5f_pow_old_pmx #SPLIT96
#python step1_select.py --version v2 --year 2017 --flavour muo --logLevel INFO --ptSelection pt_3.5_-1   --sample ST_tchannel_top_5f_pow #SPLIT45
#python step1_select.py --version v2 --year 2017 --flavour muo --logLevel INFO --ptSelection pt_3.5_-1   --sample ST_tW_antitop_NoFullyHad_5f_pow_PS #SPLIT48
#python step1_select.py --version v2 --year 2017 --flavour muo --logLevel INFO --ptSelection pt_3.5_-1   --sample ST_tW_antitop_incl_5f_pow #SPLIT67
#python step1_select.py --version v2 --year 2017 --flavour muo --logLevel INFO --ptSelection pt_3.5_-1   --sample ST_tW_antitop_incl_5f_pow_PS #SPLIT75
#python step1_select.py --version v2 --year 2017 --flavour muo --logLevel INFO --ptSelection pt_3.5_-1   --sample ST_tW_top_NoFullyHad_5f_pow #SPLIT47
#python step1_select.py --version v2 --year 2017 --flavour muo --logLevel INFO --ptSelection pt_3.5_-1   --sample ST_tW_top_NoFullyHad_5f_pow_PS #SPLIT44
#python step1_select.py --version v2 --year 2017 --flavour muo --logLevel INFO --ptSelection pt_3.5_-1   --sample ST_tW_top_incl_5f_pow #SPLIT70
#python step1_select.py --version v2 --year 2017 --flavour muo --logLevel INFO --ptSelection pt_3.5_-1   --sample ST_tW_top_incl_5f_pow_PS #SPLIT57
#python step1_select.py --version v2 --year 2017 --flavour muo --logLevel INFO --ptSelection pt_3.5_-1   --sample ST_tWll_5f_LO #SPLIT21
#python step1_select.py --version v2 --year 2017 --flavour muo --logLevel INFO --ptSelection pt_3.5_-1   --sample ST_tWnunu_5f_LO #SPLIT6

#python step1_select.py --version v2 --year 2017 --flavour muo --logLevel INFO --ptSelection pt_3.5_-1   --sample TTJets_NLO #SPLIT1265
#python step1_select.py --version v2 --year 2017 --flavour muo --logLevel INFO --ptSelection pt_3.5_-1   --sample TTJets_LO #SPLIT131
#python step1_select.py --version v2 --year 2017 --flavour muo --logLevel INFO --ptSelection pt_3.5_-1   --sample TTJets_semilepFromT_LO #SPLIT526
#python step1_select.py --version v2 --year 2017 --flavour muo --logLevel INFO --ptSelection pt_3.5_-1   --sample TTJets_semilepFromTbar_LO #SPLIT654
#python step1_select.py --version v2 --year 2017 --flavour muo --logLevel INFO --ptSelection pt_3.5_-1   --sample TTJets_dilep_LO #SPLIT301
#python step1_select.py --version v2 --year 2017 --flavour muo --logLevel INFO --ptSelection pt_3.5_-1   --sample TTJets_semilepFromT_genMET150_LO #SPLIT237
#python step1_select.py --version v2 --year 2017 --flavour muo --logLevel INFO --ptSelection pt_3.5_-1   --sample TTJets_semilepFromTbar_genMET150_LO #SPLIT130
#python step1_select.py --version v2 --year 2017 --flavour muo --logLevel INFO --ptSelection pt_3.5_-1   --sample TTJets_dilep_genMET150_LO #SPLIT188
#python step1_select.py --version v2 --year 2017 --flavour muo --logLevel INFO --ptSelection pt_3.5_-1   --sample TTTo2L2Nu_pow #SPLIT77
#python step1_select.py --version v2 --year 2017 --flavour muo --logLevel INFO --ptSelection pt_3.5_-1   --sample TTTo2L2Nu_pow_PS #SPLIT526
#python step1_select.py --version v2 --year 2017 --flavour muo --logLevel INFO --ptSelection pt_3.5_-1   --sample TTToSemiLeptonic_pow #SPLIT415
#python step1_select.py --version v2 --year 2017 --flavour muo --logLevel INFO --ptSelection pt_3.5_-1   --sample TTToSemiLeptonic_pow_PS #SPLIT1086
#python step1_select.py --version v2 --year 2017 --flavour muo --logLevel INFO --ptSelection pt_3.5_-1   --sample TTHH_LO #SPLIT3
#python step1_select.py --version v2 --year 2017 --flavour muo --logLevel INFO --ptSelection pt_3.5_-1   --sample TTZH_LO #SPLIT4
#python step1_select.py --version v2 --year 2017 --flavour muo --logLevel INFO --ptSelection pt_3.5_-1   --sample TTWH_LO #SPLIT3
#python step1_select.py --version v2 --year 2017 --flavour muo --logLevel INFO --ptSelection pt_3.5_-1   --sample TTWW_LO #SPLIT3
#python step1_select.py --version v2 --year 2017 --flavour muo --logLevel INFO --ptSelection pt_3.5_-1   --sample TTWZ_LO #SPLIT3
#python step1_select.py --version v2 --year 2017 --flavour muo --logLevel INFO --ptSelection pt_3.5_-1   --sample TTZZ_LO #SPLIT3
#python step1_select.py --version v2 --year 2017 --flavour muo --logLevel INFO --ptSelection pt_3.5_-1   --sample TTJets_HT600to800_LO #SPLIT1168
#python step1_select.py --version v2 --year 2017 --flavour muo --logLevel INFO --ptSelection pt_3.5_-1   --sample TTJets_HT800to1200_LO #SPLIT577
#python step1_select.py --version v2 --year 2017 --flavour muo --logLevel INFO --ptSelection pt_3.5_-1   --sample TTJets_HT1200to2500_LO #SPLIT271
#python step1_select.py --version v2 --year 2017 --flavour muo --logLevel INFO --ptSelection pt_3.5_-1   --sample TTJets_HT2500toInf_LO #SPLIT142

