python cacheRegion.py --year 2016 --selection "lep_SR_all-jet_SR-med_met-filters" --sample  "DY" --region 0
python cacheRegion.py --year 2016 --selection "lep_SR_all-jet_SR-med_met-filters" --sample  "DY" --region 1
python cacheRegion.py --year 2016 --selection "lep_SR_all-jet_SR-med_met-filters" --sample  "DY" --region 2
python cacheRegion.py --year 2016 --selection "lep_SR_all-jet_SR-med_met-filters" --sample  "DY" --region 3
python cacheRegion.py --year 2016 --selection "lep_SR_all-jet_SR-med_met-filters" --sample  "DY" --region 4
python cacheRegion.py --year 2016 --selection "lep_SR_all-jet_SR-med_met-filters" --sample  "DY" --region 5
python cacheRegion.py --year 2016 --selection "lep_SR_all-jet_SR-med_met-filters" --sample  "DY" --region 6
python cacheRegion.py --year 2016 --selection "lep_SR_all-jet_SR-med_met-filters" --sample  "DY" --region 7
python cacheRegion.py --year 2016 --selection "lep_SR_all-jet_SR-med_met-filters" --sample  "DY" --region 8
python cacheRegion.py --year 2016 --selection "lep_SR_all-jet_SR-med_met-filters" --sample  "TTJets_DiLepton" --region 0
python cacheRegion.py --year 2016 --selection "lep_SR_all-jet_SR-med_met-filters" --sample  "TTJets_DiLepton" --region 1
python cacheRegion.py --year 2016 --selection "lep_SR_all-jet_SR-med_met-filters" --sample  "TTJets_DiLepton" --region 2
python cacheRegion.py --year 2016 --selection "lep_SR_all-jet_SR-med_met-filters" --sample  "TTJets_DiLepton" --region 3
python cacheRegion.py --year 2016 --selection "lep_SR_all-jet_SR-med_met-filters" --sample  "TTJets_DiLepton" --region 4
python cacheRegion.py --year 2016 --selection "lep_SR_all-jet_SR-med_met-filters" --sample  "TTJets_DiLepton" --region 5
python cacheRegion.py --year 2016 --selection "lep_SR_all-jet_SR-med_met-filters" --sample  "TTJets_DiLepton" --region 6
python cacheRegion.py --year 2016 --selection "lep_SR_all-jet_SR-med_met-filters" --sample  "TTJets_DiLepton" --region 7
python cacheRegion.py --year 2016 --selection "lep_SR_all-jet_SR-med_met-filters" --sample  "TTJets_DiLepton" --region 8
python cacheRegion.py --year 2016 --selection "lep_SR_all-jet_SR-med_met-filters" --sample  "WJets" --region 0
python cacheRegion.py --year 2016 --selection "lep_SR_all-jet_SR-med_met-filters" --sample  "WJets" --region 1
python cacheRegion.py --year 2016 --selection "lep_SR_all-jet_SR-med_met-filters" --sample  "WJets" --region 2
python cacheRegion.py --year 2016 --selection "lep_SR_all-jet_SR-med_met-filters" --sample  "WJets" --region 3
python cacheRegion.py --year 2016 --selection "lep_SR_all-jet_SR-med_met-filters" --sample  "WJets" --region 4
python cacheRegion.py --year 2016 --selection "lep_SR_all-jet_SR-med_met-filters" --sample  "WJets" --region 5
python cacheRegion.py --year 2016 --selection "lep_SR_all-jet_SR-med_met-filters" --sample  "WJets" --region 6
python cacheRegion.py --year 2016 --selection "lep_SR_all-jet_SR-med_met-filters" --sample  "WJets" --region 7
python cacheRegion.py --year 2016 --selection "lep_SR_all-jet_SR-med_met-filters" --sample  "WJets" --region 8
python cacheRegion.py --year 2016 --selection "lep_SR_all-jet_SR-med_met-filters" --sample  "VV" --region 0
python cacheRegion.py --year 2016 --selection "lep_SR_all-jet_SR-med_met-filters" --sample  "VV" --region 1
python cacheRegion.py --year 2016 --selection "lep_SR_all-jet_SR-med_met-filters" --sample  "VV" --region 2
python cacheRegion.py --year 2016 --selection "lep_SR_all-jet_SR-med_met-filters" --sample  "VV" --region 3
python cacheRegion.py --year 2016 --selection "lep_SR_all-jet_SR-med_met-filters" --sample  "VV" --region 4
python cacheRegion.py --year 2016 --selection "lep_SR_all-jet_SR-med_met-filters" --sample  "VV" --region 5
python cacheRegion.py --year 2016 --selection "lep_SR_all-jet_SR-med_met-filters" --sample  "VV" --region 6
python cacheRegion.py --year 2016 --selection "lep_SR_all-jet_SR-med_met-filters" --sample  "VV" --region 7
python cacheRegion.py --year 2016 --selection "lep_SR_all-jet_SR-med_met-filters" --sample  "VV" --region 8
python cacheRegion.py --year 2016 --selection "lep_SR_all-jet_SR-med_met-filters" --sample  "TTJets_SingleLepton" --region 0
python cacheRegion.py --year 2016 --selection "lep_SR_all-jet_SR-med_met-filters" --sample  "TTJets_SingleLepton" --region 1
python cacheRegion.py --year 2016 --selection "lep_SR_all-jet_SR-med_met-filters" --sample  "TTJets_SingleLepton" --region 2
python cacheRegion.py --year 2016 --selection "lep_SR_all-jet_SR-med_met-filters" --sample  "TTJets_SingleLepton" --region 3
python cacheRegion.py --year 2016 --selection "lep_SR_all-jet_SR-med_met-filters" --sample  "TTJets_SingleLepton" --region 4
python cacheRegion.py --year 2016 --selection "lep_SR_all-jet_SR-med_met-filters" --sample  "TTJets_SingleLepton" --region 5
python cacheRegion.py --year 2016 --selection "lep_SR_all-jet_SR-med_met-filters" --sample  "TTJets_SingleLepton" --region 6
python cacheRegion.py --year 2016 --selection "lep_SR_all-jet_SR-med_met-filters" --sample  "TTJets_SingleLepton" --region 7
python cacheRegion.py --year 2016 --selection "lep_SR_all-jet_SR-med_met-filters" --sample  "TTJets_SingleLepton" --region 8
python cacheRegion.py --year 2016 --selection "lep_SR_all-jet_SR-med_met-filters" --sample  "SMS" --region 0
python cacheRegion.py --year 2016 --selection "lep_SR_all-jet_SR-med_met-filters" --sample  "SMS" --region 1
python cacheRegion.py --year 2016 --selection "lep_SR_all-jet_SR-med_met-filters" --sample  "SMS" --region 2
python cacheRegion.py --year 2016 --selection "lep_SR_all-jet_SR-med_met-filters" --sample  "SMS" --region 3
python cacheRegion.py --year 2016 --selection "lep_SR_all-jet_SR-med_met-filters" --sample  "SMS" --region 4
python cacheRegion.py --year 2016 --selection "lep_SR_all-jet_SR-med_met-filters" --sample  "SMS" --region 5
python cacheRegion.py --year 2016 --selection "lep_SR_all-jet_SR-med_met-filters" --sample  "SMS" --region 6
python cacheRegion.py --year 2016 --selection "lep_SR_all-jet_SR-med_met-filters" --sample  "SMS" --region 7
python cacheRegion.py --year 2016 --selection "lep_SR_all-jet_SR-med_met-filters" --sample  "SMS" --region 8
python cacheRegion.py --year 2016 --selection "lep_SR_all-jet_SR-med_met-filters" --sample  "Data" --region 0
python cacheRegion.py --year 2016 --selection "lep_SR_all-jet_SR-med_met-filters" --sample  "Data" --region 1
python cacheRegion.py --year 2016 --selection "lep_SR_all-jet_SR-med_met-filters" --sample  "Data" --region 2
python cacheRegion.py --year 2016 --selection "lep_SR_all-jet_SR-med_met-filters" --sample  "Data" --region 3
python cacheRegion.py --year 2016 --selection "lep_SR_all-jet_SR-med_met-filters" --sample  "Data" --region 4
python cacheRegion.py --year 2016 --selection "lep_SR_all-jet_SR-med_met-filters" --sample  "Data" --region 5
python cacheRegion.py --year 2016 --selection "lep_SR_all-jet_SR-med_met-filters" --sample  "Data" --region 6
python cacheRegion.py --year 2016 --selection "lep_SR_all-jet_SR-med_met-filters" --sample  "Data" --region 7
python cacheRegion.py --year 2016 --selection "lep_SR_all-jet_SR-med_met-filters" --sample  "Data" --region 8
